export enum RoutesEnum {
  authRouter = 'authRouter',
  mainRouter = 'mainRouter',
  welcome = 'welcome',
  login = 'login',
  register = 'register',
  verification = 'verification',
  paymentMethod = 'paymentMethod',
  paymentScreensTab = 'paymentScreensTab',
  letsyouin = 'letsyouin',
  test = 'test',
  home = 'home',
  card = 'card',
  fillprofil = 'fillprofil',
  modalScreen = 'modalScreen',
}
